name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  # Build job
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.126.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          path: public/
          fetch-depth: 0
          ref: gh-pages

      - name: Build
        run: |
          rm -rf public/* 
          hugo --gc --minify
          touch public/.nojekyll

      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd public
          git add --all
          (git commit -m "deployment" && git push) || true

